baseURL = "https://www.xiaobinqt.cn"
# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# website title
# 网站标题
title = "xiaobinqt 博客 - 技术改变生活"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = true
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

# ignore some build errors
# 忽略一些构建错误
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# theme
# 主题
theme = "do"
# themes directory
# 主题目录
themesDir = "themes"

# Or, when using theme as hugo module
# [module]
# [[module.imports]]
# path = "github.com/xiaobinqt.github.io"

capitalizeListTitles = false
