# Menu config
# 菜单配置

[[main]]
  identifier = "posts"
  # you can add extra information before the name (HTML format is supported), such as icons
  # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
  post = ""
  name = "所有文章"
  url = "/posts/"
  # title will be shown when you hover on this menu link.
  # 将鼠标悬停在此菜单链接上时将显示标题。
  title = ""
  weight = 1
[[main]]
  identifier = "tags"
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = ""
  weight = 2
[[main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = ""
  weight = 3
[[main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "系列"
  url = "/series/"
  title = ""
  weight = 4
[[main]]
  identifier = "showcase"
  pre = ""
  post = ""
  name = "小册"
  url = "/showcase/"
  title = ""
  weight = 5
[[main]]
    identifier = "keeplearning"
    pre = ""
    post = ""
    name = "KeepLearning"
    url = "/keeplearning/-open-blank-target"
    title = ""
    weight = 6
[[main]]
    identifier = "leetcode"
    pre = ""
    post = ""
    name = "LeetCode"
    url = "/leetcode/-open-blank-target"
    title = ""
    weight = 7
[[main]]
    identifier = "links"
    pre = ""
    post = ""
    name = "友链"
    url = "/links/"
    title = ""
    weight = 8
[[main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 9
[[main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/xiaobinqt"
    title = "GitHub"
    weight = 10





