name: Algolia upload
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - main
jobs:
  build:
    runs-on: ubuntu-latest # 镜像市场
    steps:
      - name: checkout # 步骤的名称
        uses: actions/checkout@v1 #软件市场的名称

      - uses: rxrw/algolia-index-uploader@v1
        with:
          index_path: "public/index.json"
          algolia_index_id: "U8I48S9K50"
          algolia_index_name: "blog"
          algolia_index_admin_key: "37c83723f2f817858bced8d58e052fe0"
