name: algolia-upload

on:
  - push

jobs:
  upload_hugo_algolia_index:
    runs-on: ubuntu-latest
    name: Upload Hugo Algolia Index
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: aoudiamoncef/hugo-algolia-uploader@main
        with:
          # Such as `LAHZOUZT15`. Required
          app_id: xiaobin2
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ALGOLIA_ADMIN_KEY }} . Required
          admin_key: 37c83723f2f817858bced8d58e052fe0
          # The index name. Required
          index_name: blog